options:
  lineNumbers: true
  spellcheck: true
  askImageFilename: true
  imagePrefix: 20xx-xx-xx_xxxxx
  imagePath: /img
editor:
  lineNumbers: true
  inputStyle: contenteditable
  spellcheck: true
